<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="UserManagerWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/UserManagerWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/UserManagerWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="www.usermanagerws.com">
    <import location="../127.0.0.1_8080/IS-TP2-EJB/UserManager.wsdl" namespace="www.usermanagerws.com"/>
    <plnk:partnerLinkType name="UserManagerLinkType">
        <plnk:role name="UserManagerRole" portType="ns:UserManager"/>
    </plnk:partnerLinkType>
</definitions>
