
package org.netbeans.j2ee.wsdl.lpco_bpel_module.processorquestratorusermanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserExistsPortType", targetNamespace = "http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrquestratorUserManager")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface UserExistsPortType {


    /**
     * 
     * @param username
     * @return
     *     returns org.netbeans.j2ee.wsdl.lpco_bpel_module.processorquestratorusermanager.UserExistsResponseType
     */
    @WebMethod(operationName = "UserExistsOperation")
    @WebResult(name = "UserExistsOperationResponse", partName = "UserExistsOperationResponse")
    public UserExistsResponseType userExistsOperation(
        @WebParam(name = "username", partName = "username")
        String username);

}
