
package org.netbeans.j2ee.wsdl.lpco_bpel_module.processorchestratorordersmanager;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ProcessOrchestratorOrdersManagerService", targetNamespace = "http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrchestratorOrdersManager", wsdlLocation = "http://localhost:9080/ProcessOrchestratorOrdersManagerService/GetOrdersOfUserPort?wsdl")
public class ProcessOrchestratorOrdersManagerService
    extends Service
{

    private final static URL PROCESSORCHESTRATORORDERSMANAGERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.netbeans.j2ee.wsdl.lpco_bpel_module.processorchestratorordersmanager.ProcessOrchestratorOrdersManagerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.netbeans.j2ee.wsdl.lpco_bpel_module.processorchestratorordersmanager.ProcessOrchestratorOrdersManagerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9080/ProcessOrchestratorOrdersManagerService/GetOrdersOfUserPort?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9080/ProcessOrchestratorOrdersManagerService/GetOrdersOfUserPort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROCESSORCHESTRATORORDERSMANAGERSERVICE_WSDL_LOCATION = url;
    }

    public ProcessOrchestratorOrdersManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessOrchestratorOrdersManagerService() {
        super(PROCESSORCHESTRATORORDERSMANAGERSERVICE_WSDL_LOCATION, new QName("http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrchestratorOrdersManager", "ProcessOrchestratorOrdersManagerService"));
    }

    /**
     * 
     * @return
     *     returns OrderReadyPortType
     */
    @WebEndpoint(name = "OrderReadyPort")
    public OrderReadyPortType getOrderReadyPort() {
        return super.getPort(new QName("http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrchestratorOrdersManager", "OrderReadyPort"), OrderReadyPortType.class);
    }

    /**
     * 
     * @return
     *     returns CheckOutPortType
     */
    @WebEndpoint(name = "CheckOutPort")
    public CheckOutPortType getCheckOutPort() {
        return super.getPort(new QName("http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrchestratorOrdersManager", "CheckOutPort"), CheckOutPortType.class);
    }

    /**
     * 
     * @return
     *     returns GetOrdersOfUserPortType
     */
    @WebEndpoint(name = "GetOrdersOfUserPort")
    public GetOrdersOfUserPortType getGetOrdersOfUserPort() {
        return super.getPort(new QName("http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrchestratorOrdersManager", "GetOrdersOfUserPort"), GetOrdersOfUserPortType.class);
    }

}
