
package org.netbeans.j2ee.wsdl.lpco_bpel_module.processorchestratorcatalogmanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SearchCameraPortType", targetNamespace = "http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrchestratorCatalogManager")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SearchCameraPortType {


    /**
     * 
     * @param cameraName
     * @return
     *     returns org.netbeans.j2ee.wsdl.lpco_bpel_module.processorchestratorcatalogmanager.SearchCameraResponse
     * @throws SearchCameraOperationFault
     */
    @WebMethod(operationName = "SearchCameraOperation")
    @WebResult(name = "SearchCameraOperationResponse", partName = "SearchCameraOperationResponse")
    public SearchCameraResponse searchCameraOperation(
        @WebParam(name = "CameraName", partName = "CameraName")
        String cameraName)
        throws SearchCameraOperationFault
    ;

}
