
package org.netbeans.j2ee.wsdl.lpco_bpel_module.processorchestratorcatalogmanager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "ErrorMessage", targetNamespace = "http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrchestratorCatalogManager")
public class SearchCameraOperationFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorMessage faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SearchCameraOperationFault(String message, ErrorMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SearchCameraOperationFault(String message, ErrorMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.netbeans.j2ee.wsdl.lpco_bpel_module.processorchestratorcatalogmanager.ErrorMessage
     */
    public ErrorMessage getFaultInfo() {
        return faultInfo;
    }

}
