
package org.netbeans.j2ee.wsdl.lpco_bpel_module.processorquestratorusermanager;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ProcessOrquestratorUserManagerService", targetNamespace = "http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrquestratorUserManager", wsdlLocation = "http://localhost:9080/ProcessOrchestratorUserManagerService/UserExistsPort?wsdl")
public class ProcessOrquestratorUserManagerService
    extends Service
{

    private final static URL PROCESSORQUESTRATORUSERMANAGERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.netbeans.j2ee.wsdl.lpco_bpel_module.processorquestratorusermanager.ProcessOrquestratorUserManagerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.netbeans.j2ee.wsdl.lpco_bpel_module.processorquestratorusermanager.ProcessOrquestratorUserManagerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9080/ProcessOrchestratorUserManagerService/UserExistsPort?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9080/ProcessOrchestratorUserManagerService/UserExistsPort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROCESSORQUESTRATORUSERMANAGERSERVICE_WSDL_LOCATION = url;
    }

    public ProcessOrquestratorUserManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessOrquestratorUserManagerService() {
        super(PROCESSORQUESTRATORUSERMANAGERSERVICE_WSDL_LOCATION, new QName("http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrquestratorUserManager", "ProcessOrquestratorUserManagerService"));
    }

    /**
     * 
     * @return
     *     returns LoginUserPortType
     */
    @WebEndpoint(name = "LoginUserPort")
    public LoginUserPortType getLoginUserPort() {
        return super.getPort(new QName("http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrquestratorUserManager", "LoginUserPort"), LoginUserPortType.class);
    }

    /**
     * 
     * @return
     *     returns UserExistsPortType
     */
    @WebEndpoint(name = "UserExistsPort")
    public UserExistsPortType getUserExistsPort() {
        return super.getPort(new QName("http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrquestratorUserManager", "UserExistsPort"), UserExistsPortType.class);
    }

    /**
     * 
     * @return
     *     returns AddUserPortType
     */
    @WebEndpoint(name = "AddUserPort")
    public AddUserPortType getAddUserPort() {
        return super.getPort(new QName("http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrquestratorUserManager", "AddUserPort"), AddUserPortType.class);
    }

}
