
package org.netbeans.j2ee.wsdl.lpco_bpel_module.processorchestratorordersmanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ShipOrderPortType", targetNamespace = "http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrchestratorOrdersManager")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ShipOrderPortType {


    /**
     * 
     * @param shipOrderOperationRequest
     * @return
     *     returns org.netbeans.j2ee.wsdl.lpco_bpel_module.processorchestratorordersmanager.ShipOrderResponseType
     */
    @WebMethod(operationName = "ShipOrderOperation")
    @WebResult(name = "ShipOrderResponse", partName = "ShipOrderResponse")
    public ShipOrderResponseType shipOrderOperation(
        @WebParam(name = "ShipOrderOperationRequest", partName = "ShipOrderOperationRequest")
        OrderToShip shipOrderOperationRequest);

}
