<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="OrdersManagerWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/OrdersManagerWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/OrdersManagerWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="www.ordersmanagerws.com">
    <import location="../127.0.0.1_8080/IS-TP2-EJB/OrdersManager.wsdl" namespace="www.ordersmanagerws.com"/>
    <plnk:partnerLinkType name="OrdersManagerLinkType">
        <plnk:role name="OrdersManagerRole" portType="ns:OrdersManager"/>
    </plnk:partnerLinkType>
</definitions>
