<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ShippingBeanWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ShippingBeanWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ShippingBeanWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="www.shippingdepartmentws.com">
    <import location="../127.0.0.1_8080/ShippingDepartmentWS/ShippingBean.wsdl" namespace="www.shippingdepartmentws.com"/>
    <plnk:partnerLinkType name="ShippingBeanLinkType">
        <plnk:role name="ShippingBeanRole" portType="ns:ShippingBean"/>
    </plnk:partnerLinkType>
</definitions>
