
package org.netbeans.j2ee.wsdl.lpco_bpel_module.processorchestratorcatalogmanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GetCameraPortType", targetNamespace = "http://j2ee.netbeans.org/wsdl/LPCO_BPEL_MODULE/ProcessOrchestratorCatalogManager")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface GetCameraPortType {


    /**
     * 
     * @param cameraID
     * @return
     *     returns org.netbeans.j2ee.wsdl.lpco_bpel_module.processorchestratorcatalogmanager.Camera
     */
    @WebMethod(operationName = "GetCameraOperation")
    @WebResult(name = "GetCameraOperationResponse", partName = "GetCameraOperationResponse")
    public Camera getCameraOperation(
        @WebParam(name = "cameraID", partName = "cameraID")
        int cameraID);

}
